import { jsPDF } from 'jspdf';

export const exportDietChartToPDF = (dietPlans: any[], patientName: string) => {
  const doc = new jsPDF();
  
  // Title
  doc.setFontSize(20);
  doc.text('Ayurvedic Diet Chart', 105, 20, { align: 'center' });
  
  // Patient Info
  doc.setFontSize(12);
  doc.text(`Patient: ${patientName}`, 20, 35);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 42);
  
  let yPosition = 55;
  
  // Diet Plans
  dietPlans.forEach((plan, index) => {
    if (yPosition > 250) {
      doc.addPage();
      yPosition = 20;
    }
    
    doc.setFontSize(14);
    doc.setFont(undefined, 'bold');
    doc.text(plan.mealTime, 20, yPosition);
    yPosition += 8;
    
    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    
    if (plan.foods && plan.foods.length > 0) {
      plan.foods.forEach((food: any) => {
        if (yPosition > 270) {
          doc.addPage();
          yPosition = 20;
        }
        doc.text(`• ${food.name} (${food.serving})`, 25, yPosition);
        yPosition += 5;
        doc.setFontSize(9);
        doc.text(`  Calories: ${food.calories} | P: ${food.protein}g | C: ${food.carbs}g | F: ${food.fat}g`, 30, yPosition);
        yPosition += 7;
        doc.setFontSize(10);
      });
    } else {
      doc.text('No foods added', 25, yPosition);
      yPosition += 7;
    }
    
    yPosition += 5;
  });
  
  // Footer
  doc.setFontSize(8);
  doc.text('Generated by AyurAgent - Ayurvedic Practice Management System', 105, 285, { align: 'center' });
  
  doc.save(`diet-chart-${patientName}-${new Date().getTime()}.pdf`);
};

export const exportPatientProfileToPDF = (patient: any) => {
  const doc = new jsPDF();
  
  // Title
  doc.setFontSize(20);
  doc.text('Patient Profile', 105, 20, { align: 'center' });
  
  let yPosition = 35;
  
  // Basic Info
  doc.setFontSize(14);
  doc.setFont(undefined, 'bold');
  doc.text('Basic Information', 20, yPosition);
  yPosition += 8;
  
  doc.setFontSize(11);
  doc.setFont(undefined, 'normal');
  doc.text(`Name: ${patient.name}`, 20, yPosition);
  yPosition += 7;
  doc.text(`Age: ${patient.age} years`, 20, yPosition);
  yPosition += 7;
  doc.text(`Gender: ${patient.gender}`, 20, yPosition);
  yPosition += 7;
  doc.text(`Primary Dosha: ${patient.dosha}`, 20, yPosition);
  yPosition += 7;
  doc.text(`Email: ${patient.email}`, 20, yPosition);
  yPosition += 7;
  doc.text(`Phone: ${patient.phone}`, 20, yPosition);
  yPosition += 12;
  
  // Health Metrics
  doc.setFontSize(14);
  doc.setFont(undefined, 'bold');
  doc.text('Health Metrics', 20, yPosition);
  yPosition += 8;
  
  doc.setFontSize(11);
  doc.setFont(undefined, 'normal');
  doc.text(`Dietary Habits: ${patient.dietaryHabits}`, 20, yPosition);
  yPosition += 7;
  doc.text(`Meal Frequency: ${patient.mealFrequency} times/day`, 20, yPosition);
  yPosition += 7;
  doc.text(`Water Intake: ${patient.waterIntake}L/day`, 20, yPosition);
  yPosition += 7;
  doc.text(`Sleep Hours: ${patient.sleepHours} hours`, 20, yPosition);
  yPosition += 7;
  doc.text(`Bowel Movement: ${patient.bowelMovement}`, 20, yPosition);
  yPosition += 7;
  doc.text(`Exercise Frequency: ${patient.exerciseFrequency}`, 20, yPosition);
  yPosition += 12;
  
  // Medical History
  doc.setFontSize(14);
  doc.setFont(undefined, 'bold');
  doc.text('Medical History', 20, yPosition);
  yPosition += 8;
  
  doc.setFontSize(11);
  doc.setFont(undefined, 'normal');
  doc.text('Medical Conditions:', 20, yPosition);
  yPosition += 7;
  if (patient.medicalConditions && patient.medicalConditions.length > 0) {
    patient.medicalConditions.forEach((condition: string) => {
      doc.text(`• ${condition}`, 25, yPosition);
      yPosition += 6;
    });
  } else {
    doc.text('None', 25, yPosition);
    yPosition += 6;
  }
  yPosition += 5;
  
  doc.text('Allergies:', 20, yPosition);
  yPosition += 7;
  if (patient.allergies && patient.allergies.length > 0) {
    patient.allergies.forEach((allergy: string) => {
      doc.text(`• ${allergy}`, 25, yPosition);
      yPosition += 6;
    });
  } else {
    doc.text('None', 25, yPosition);
    yPosition += 6;
  }
  yPosition += 5;
  
  doc.text('Current Medications:', 20, yPosition);
  yPosition += 7;
  if (patient.currentMedications && patient.currentMedications.length > 0) {
    patient.currentMedications.forEach((med: string) => {
      doc.text(`• ${med}`, 25, yPosition);
      yPosition += 6;
    });
  } else {
    doc.text('None', 25, yPosition);
    yPosition += 6;
  }
  
  // Footer
  doc.setFontSize(8);
  doc.text('Generated by AyurAgent - Ayurvedic Practice Management System', 105, 285, { align: 'center' });
  
  doc.save(`patient-profile-${patient.name}-${new Date().getTime()}.pdf`);
};
