import { useAuth } from './useAuth';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export const usePDFExport = () => {
  const { user } = useAuth();

  const exportToPDF = async (consultationData: any) => {
    if (!consultationData) {
      throw new Error('No consultation data to export');
    }

    const doc = new jsPDF();
    const timestamp = new Date().toLocaleString();
    const pageWidth = doc.internal.pageSize.getWidth();
    
    doc.setFontSize(24);
    doc.setTextColor(139, 115, 85);
    doc.text('AYURAGENT', pageWidth / 2, 20, { align: 'center' });
    doc.setFontSize(12);
    doc.setTextColor(100, 100, 100);
    doc.text('Personalized Wellness Report', pageWidth / 2, 28, { align: 'center' });
    
    doc.setDrawColor(139, 115, 85);
    doc.line(20, 32, pageWidth - 20, 32);
    
    doc.setFontSize(10);
    doc.setTextColor(80, 80, 80);
    doc.text(`Report Generated: ${timestamp}`, 20, 42);
    doc.text(`Patient: ${user?.email || 'Anonymous'}`, 20, 48);
    
    doc.setFontSize(14);
    doc.setTextColor(139, 115, 85);
    doc.text('DOSHA ANALYSIS', 20, 60);
    
    doc.setFontSize(11);
    doc.setTextColor(60, 60, 60);
    const primaryDosha = consultationData.dosha || 'Not determined';
    doc.text(`Primary Dosha: ${primaryDosha}`, 20, 68);
    
    autoTable(doc, {
      startY: 75,
      head: [['Characteristic', 'When Balanced', 'When Imbalanced']],
      body: [[getDoshaCharacteristics(primaryDosha), getDoshaBalanced(primaryDosha), getDoshaImbalanced(primaryDosha)]],
      theme: 'grid',
      headStyles: { fillColor: [139, 115, 85], textColor: 255 },
      styles: { fontSize: 9, cellPadding: 3 }
    });
    
    const finalY = (doc as any).lastAutoTable?.finalY || 100;
    doc.setFontSize(14);
    doc.setTextColor(139, 115, 85);
    doc.text('DAILY ROUTINE PLAN', 20, finalY + 15);
    
    const dailyRoutine = consultationData.recommendations?.dailyRoutine;
    if (dailyRoutine) {
      autoTable(doc, {
        startY: finalY + 20,
        head: [['Time', 'Activities']],
        body: [
          ['Morning (6-10 AM)', dailyRoutine.morning?.join(', ') || 'Meditation, light exercise'],
          ['Afternoon (10-6 PM)', dailyRoutine.afternoon?.join(', ') || 'Main meal, work activities'],
          ['Evening (6-10 PM)', dailyRoutine.evening?.join(', ') || 'Light dinner, relaxation']
        ],
        theme: 'grid',
        headStyles: { fillColor: [139, 115, 85], textColor: 255 },
        styles: { fontSize: 9, cellPadding: 3 }
      });
    }
    
    const dietY = (doc as any).lastAutoTable?.finalY || finalY + 50;
    if (dietY > 220) doc.addPage();
    
    doc.setFontSize(14);
    doc.setTextColor(139, 115, 85);
    doc.text('DIET RECOMMENDATIONS', 20, dietY > 220 ? 20 : dietY + 15);
    
    const diet = consultationData.recommendations?.diet;
    if (diet) {
      autoTable(doc, {
        startY: dietY > 220 ? 25 : dietY + 20,
        head: [['Category', 'Recommendations']],
        body: [
          ['Foods to Favor', diet.include?.join(', ') || 'Warm, cooked foods'],
          ['Foods to Avoid', diet.avoid?.join(', ') || 'Processed foods'],
          ['Guidelines', 'Eat mindfully, regular meal times']
        ],
        theme: 'grid',
        headStyles: { fillColor: [139, 115, 85], textColor: 255 },
        styles: { fontSize: 9, cellPadding: 3 }
      });
    }
    
    doc.setFontSize(9);
    doc.setTextColor(120, 120, 120);
    doc.text('DISCLAIMER: This report provides general Ayurvedic guidance.', 20, 260);
    doc.text('Not a substitute for professional medical advice.', 20, 266);
    
    doc.setFontSize(9);
    doc.setTextColor(100, 100, 100);
    doc.text('Generated by AyurAgent', pageWidth / 2, 285, { align: 'center' });
    
    const dateStr = new Date().toISOString().split('T')[0];
    doc.save(`AyurAgent-Report-${dateStr}.pdf`);
  };

  const getDoshaCharacteristics = (dosha: string) => {
    switch (dosha) {
      case 'Vata':
        return 'Quick thinking, creative, energetic';
      case 'Pitta':
        return 'Focused, ambitious, strong digestion';
      case 'Kapha':
        return 'Calm, steady, strong immunity';
      default:
        return '';
    }
  };

  const getDoshaBalanced = (dosha: string) => {
    switch (dosha) {
      case 'Vata':
        return 'Alert, creative, flexible';
      case 'Pitta':
        return 'Intelligent, confident, good leader';
      case 'Kapha':
        return 'Peaceful, stable, loving';
      default:
        return '';
    }
  };

  const getDoshaImbalanced = (dosha: string) => {
    switch (dosha) {
      case 'Vata':
        return 'Anxious, restless, constipation';
      case 'Pitta':
        return 'Irritable, inflammatory conditions';
      case 'Kapha':
        return 'Sluggish, weight gain, depression';
      default:
        return '';
    }
  };

  const exportConsultationHistory = async (messages: any[], dosha?: string) => {
    if (!messages || messages.length === 0) {
      throw new Error('No conversation history to export');
    }

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    
    doc.setFontSize(20);
    doc.setTextColor(139, 115, 85);
    doc.text('AYURAGENT', pageWidth / 2, 20, { align: 'center' });
    
    doc.setFontSize(12);
    doc.setTextColor(100, 100, 100);
    doc.text('Consultation Chat History', pageWidth / 2, 28, { align: 'center' });
    
    doc.setFontSize(10);
    doc.setTextColor(80, 80, 80);
    doc.text(`Export Date: ${new Date().toLocaleString()}`, 20, 40);
    doc.text(`Patient: ${user?.email || 'Anonymous'}`, 20, 46);
    if (dosha) {
      doc.text(`Primary Dosha: ${dosha}`, 20, 52);
    }
    doc.text(`Total Messages: ${messages.length}`, 20, dosha ? 58 : 52);
    
    const conversationData = messages.map((message) => [
      new Date(message.timestamp).toLocaleString(),
      message.sender === 'user' ? 'Patient' : 'AyurAgent',
      message.text.substring(0, 200) + (message.text.length > 200 ? '...' : '')
    ]);
    
    autoTable(doc, {
      startY: dosha ? 65 : 60,
      head: [['Time', 'Sender', 'Message']],
      body: conversationData,
      theme: 'grid',
      headStyles: { fillColor: [139, 115, 85], textColor: 255 },
      styles: { fontSize: 8, cellPadding: 2 },
      columnStyles: {
        0: { cellWidth: 35 },
        1: { cellWidth: 25 },
        2: { cellWidth: pageWidth - 85 }
      }
    });
    
    const finalY = (doc as any).lastAutoTable?.finalY || 100;
    doc.setFontSize(9);
    doc.setTextColor(120, 120, 120);
    doc.text('This consultation history contains personal health information. Please keep it confidential.', 20, finalY + 15);
    
    doc.setFontSize(9);
    doc.setTextColor(100, 100, 100);
    doc.text('Generated by AyurAgent', pageWidth / 2, 285, { align: 'center' });
    
    const dateStr = new Date().toISOString().split('T')[0];
    doc.save(`AyurAgent-Chat-History-${dateStr}.pdf`);
  };

  return {
    exportToPDF,
    exportConsultationHistory
  };
};