// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://osxdhefsygauonydhgiz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9zeGRoZWZzeWdhdW9ueWRoZ2l6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2OTM1OTAsImV4cCI6MjA3MzI2OTU5MH0.xYuzmwIfQNvqHpEghWSKcev9NQ7Yr1_aYTDPtCyQu4k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});